apiVersion: v1
kind: Pod
metadata:
  name: bitcoin
  namespace: default
spec:
  containers:
  - name: bitcoin
    image: luciane/bitcoin:1.0
    ports:
      - containerPort: 5000
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: dolar
  namespace: default
  labels:
    app: dolar
spec:
  containers:
  - name: dolar
    image: luciane/dolar:1.0
    ports:
      - containerPort: 5000
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    env:
      - name: BITCOIN_ENDPOINT
        value: http://172.18.0.1:5001


